### ISSUE TITLE
gulp-header update bug

### ISSUE THREAD

**Issue by benjamincanac** [miickel/gulp-angular-templatecache#124]
Hi,

An hour ago the gulp-header module has been updated to v1.8.3 but it broke templatecache.

Can you fix the version ?

Thanks.

**Comment by benjamincanac** [comment]
#125

**Comment by bbuhler** [comment]
Seems to be caused by this commit https://github.com/tracker1/gulp-header/commit/7feb21151e9101baa47a5ce61d3d6dbc7b975b08.

**Comment by philjones88** [comment]
Same issue here. Resorted to `npm shrinkwrap` and defining version 1.8.2 of this package.

**Comment by doofer** [comment]
So an alternative solution, until this is accepted, is to include the    
` "gulp-header": "1.8.2",` in package.json

**Comment by bondarewicz** [comment]
are you guys getting something along those lines? :
```
fs.js:839
[12:13:17][Step 8/14]   return binding.lstat(pathModule._makeLong(path));
[12:13:17][Step 8/14]                  ^
[12:13:17][Step 8/14] 
[12:13:17][Step 8/14] Error: ENOENT: no such file or directory, lstat 'C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\src\app\templateCacheHtml.js'
[12:13:17][Step 8/14]     at Error (native)
[12:13:17][Step 8/14]     at Object.fs.lstatSync (fs.js:839:18)
[12:13:17][Step 8/14]     at DestroyableTransform.TransformStream [as _transform] (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-header\index.js:38:12)
[12:13:17][Step 8/14]     at DestroyableTransform.Transform._read (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-header\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
[12:13:17][Step 8/14]     at DestroyableTransform.Transform._write (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-header\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
[12:13:17][Step 8/14]     at doWrite (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-header\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
[12:13:17][Step 8/14]     at writeOrBuffer (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-header\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
[12:13:17][Step 8/14]     at DestroyableTransform.Writable.write (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-header\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
[12:13:17][Step 8/14]     at write (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-concat\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
[12:13:17][Step 8/14]     at flow (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-concat\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
[12:13:17][Step 8/14]     at DestroyableTransform.pipeOnReadable (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-concat\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
[12:13:17][Step 8/14]     at emitNone (events.js:67:13)
[12:13:17][Step 8/14]     at DestroyableTransform.emit (events.js:166:7)
[12:13:17][Step 8/14]     at emitReadable_ (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-concat\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
[12:13:17][Step 8/14]     at emitReadable (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-concat\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
[12:13:17][Step 8/14]     at readableAddChunk (C:\TeamCity\buildAgent\work\eb5dfb8f3a5dbb94\node_modules\gulp-angular-templatecache\node_modules\gulp-concat\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
```

**Comment by curvedental** [comment]
We worked around the issue by installing gulp-header@1.8.2 as well

**Comment by grtjn** [comment]
Observing it too: https://github.com/marklogic/slush-marklogic-node/issues/365

**Comment by grtjn** [comment]
Creating an empty file in the spot gulp-header is looking also works as work-around, but I like reverting to 1.8.2 better..

**Comment by warlyware** [comment]
This is the error I was getting all morning:
```
fs.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy

Error: ENOENT, no such file or directory '/var/www/src/templates.js'
```
and ```"gulp-header"``` was the culprit.  Adding ```"gulp-header": "1.8.2"``` to package.json fixed it.  Thanks all.

**Comment by gamebox** [comment]
@warlyware This worked by adding to your own application's package.json?

**Comment by mikejr83** [comment]
We've been bitten by this issue as well. Can confirm that adding gulp-header@1.8.2 to our package.json short-circuits node into using that version for the dependency resolution.

**Comment by SamMorrowDrums** [comment]
Considering npm shrinkwrap myself now! Not the first time I've been bitten by things like that!

**Comment by grtjn** [comment]
That worked for us, just put gulp-header above gulp-angular-templatecache, npm uninstall gulp-angular-templatecache, and do npm install..

**Comment by infodark** [comment]
Same problem here. Adding "gulp-header": "1.8.2" to package.json worked for me.

**Comment by clocked0ne** [comment]
Why do they do this on a Friday afternoon??? >:( :-1:

**Comment by DinisCruz** [comment]
yes that also worked for me

![image](https://cloud.githubusercontent.com/assets/656739/16158702/5f3ad5c2-34b6-11e6-80da-6819097bb856.png)

what was the root cause of the problem?

**Comment by alejandrolechuga** [comment]
gulp-header: 1.8.2 worked

**Comment by grtjn** [comment]
Root cause is in gulp-header, see also https://github.com/tracker1/gulp-header/issues/37

**Comment by andrewcurtis-mris** [comment]
I would propose that the true deficiency here are the loose dependency definitions. With all of this project's dependencies defined as 1.x or 2.x etc this project will be subject to pulling in any defects introduced in any of its downstream dependencies at any time. This one just happened to be in gulp-headers 1.8.3

**Comment by nkanand4** [comment]
There are more like this, just waiting for others to break when the deps change.
`    "gulp-footer": "1.x",
    "gulp-header": "1.x",
    "gulp-concat": "2.x"`

**Comment by spg** [comment]
gulp-header: 1.8.2 worked for me too, thx for reporting this problem. This saved my team a lot of time.

**Comment by candyam5522** [comment]
gulp-header: 1.8.2 worked for me

**Comment by Schwankenson** [comment]
gulp-header: 1.8.2 worked for me too, thx for reporting this problem. This saved my team a lot of time.

**Comment by evankleist** [comment]
Well I spent my whole day trying to fix this, thinking it was a problem with my gulp tasks. At least I finally found this thread

**Comment by SamMorrowDrums** [comment]
Haha, I spent too long on it too. I set up CI server to run with Upstart,
then had issues with npm and no $HOME environmental variable, and then hit
this!

Initially I just assumed any issues were my fault...

**Comment by sandy724** [comment]
Is there a better way to figure out these kinds of issue, what is the approach to debug such issues. I luckily stumbled on this thread otherwise I didn't had any direction where to look.

**Comment by mydata** [comment]
Even i was also spent almost whole day thinking it was due to other reasons like folder permission, node server issues , gup issues etc. At last found this thread and applied the temporary fix and got the build working.

**Comment by SamMorrowDrums** [comment]
The appropriate way to debug this is really:

- Read the stack trace (the fs command showed the library call in which it
broke)
- look at the code on the mentioned line
- double check your calling code, just in case something has changed
- check npm for version changes (going back through the stack trace if
required)
- Revert dep if required

The problem is, we developers often work from the assumption that if you
encounter an error, it is always in your code, while the reality is
libraries can be at fault.

Some advice:
- _believe stack traces_, the library code call stack, can be the source of
the error.
- take a deep breath when debugging streams, particularly when you only
wrote the plumbing code, and all the streaming is in third party libraries,
the async stack traces can be really poor, but they almost always hint at
the answer.

The systemic problem, is that npm allows packages to be published with
loose semver for their deps. Personally, while it takes burden off
publishers, it does so at the cost of reliability. Shrinkwrap is a good
call for production apps or at least strict dependencies in your
package.json, which would let you eliminate first layer of dependencies
having changed.

**Comment by cfrezier** [comment]
Putting gulp-header: 1.8.2 above gulp-angular-templatecache worked for me

**Comment by alexda14** [comment]
:scream_cat: 
But, ```gulp-header: 1.8.2``` works

**Comment by miickel** [comment]
A fix is on the way to NPM now. 🚀 Thanks for brining this to my attention!

**Comment by tabladrum** [comment]
still breaking. Is it there yet?

**Comment by miickel** [comment]
@tabladrum make sure you have 1.9.0 installed

`cat node_modules/gulp-angular-templatecache/package.json | grep version`

**Comment by tabladrum** [comment]
👍 Thanks!

**Comment by Soumya-mp** [comment]
This is still breaking....
