### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by grtjn** [miickel/gulp-angular-templatecache#129]
After working around the gulp-header issue described in #124, I am getting this today:

```
[23:59:15] Starting 'templatecache'...
[23:59:15] Creating an AngularJS $templateCache

.../myapp/node_modules/gulp-angular-templatecache/node_modules/jsesc/jsesc.js:3
const object = {};
^^^^^
[23:59:16] 'templatecache' errored after 288 ms
[23:59:16] SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../myapp/node_modules/gulp-angular-templatecache/index.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Not sure what changed, but gulp-header@1.8.2 together with gulp-angular-templatecache@1.8.0 seems to work better..

From package.json:
```
    "gulp-header": "1.8.2",
    "gulp-angular-templatecache": "1.8.0",
```

**Comment by grtjn** [comment]
thnx for the quick turnaround..

**Comment by carloshpds** [comment]
That's happening on `v1.9.0`:/

**Comment by grtjn** [comment]
Yes, and it got fixed with `v1.9.1`, use that instead. That version works well for me..

**Comment by Muskos** [comment]
2.0.0 that's happening.
`dev/node_modules/gulp-angular-templatecache/node_modules/jsesc/jsesc.js:3
const object = {};
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (dev/node_modules/gulp-angular-templatecache/index.js:7:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
`

**Comment by miickel** [comment]
@Muskos yes, use `v1.9.1` of this plugin if you run older versions of node (older than 4.2.x).
