### ISSUE TITLE
Gulp dies: concat-with-sourcemap: unixStylePath: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by w3bappd3v** [miickel/gulp-angular-templatecache#134]
this may be dependency related, it works on my mac node v4.4.5, npm v2.15.5  
but no go on my home windows node v6.2.2, npm v3.7.3
and no go on work windows node v4.4.7, npm v2.15.8

both windows machines have same issue 

I guess also could be file system?

mac npm doesnt even install concat-with-sourcemaps in node_modules

Logged out value of filePath in \node_modules\concat-with-sourcemaps\index.js:6:1:
FP  templates.js
FP  null

it logs twice, first value is 'templates.js', second is NULL

[14:51:36] Using gulpfile d:\code\ui-seed\gulpfile.js
[14:51:36] Starting 'default'...
D:\code\ui-seed\node_modules\concat-with-sourcemaps\index.js:6
  return filePath.replace(/\\/g, '/');
                 ^

TypeError: Cannot read property 'replace' of null
    at unixStylePath (D:\code\ui-seed\node_modules\concat-with-sourcemaps\index.js:6:18)
    at Concat.add (D:\code\ui-seed\node_modules\concat-with-sourcemaps\index.js:35:14)
    at DestroyableTransform.TransformStream [as _transform] (D:\code\ui-seed\node_modules\gulp-header\index.js:38:14)
    at DestroyableTransform.Transform._read (D:\code\ui-seed\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (D:\code\ui-seed\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\code\ui-seed\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (D:\code\ui-seed\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (D:\code\ui-seed\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at write (D:\code\ui-seed\node_modules\gulp-angular-templatecache\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (D:\code\ui-seed\node_modules\gulp-angular-templatecache\node_modules\readable-stream\lib\_stream_readable.js:632:7)

**Comment by w3bappd3v** [comment]
I fixed this by blowing away node_modules in my app and rerunning npm install
